plugins {
    id 'com.android.library'
}

android {
    namespace 'de.robv.android.xposed.api'
    compileSdk 34

    sourceSets {
        main {
            manifest.srcFile 'src/main/AndroidManifest.xml'
            java.srcDirs = ['../app/src/main/xposed']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
